In [4]:
#kannada_digit MNIST prob;em
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.decomposition import KernelPCA
from sklearn.metrics import precision_recall_fscore_support, confusion_matrix,roc_auc_score, auc
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn import datasets
from sklearn import tree
from sklearn import metrics

In [ ]:
#load MNIST dataset

data_X_train=np.load('/content/X_kannada_MNIST_train.npz')
X_train=data_X_train['arr_0']
data_X_test=np.load('/content/X_kannada_MNIST_test.npz')
X_test=data_X_test['arr_0']

data_y_train=np.load('/content/y_kannada_MNIST_train.npz')
y_train=data_y_train['arr_0']
data_y_test=np.load('/content/y_kannada_MNIST_test.npz')
y_test=data_y_test['arr_0']


In [ ]:
X_train=data_X_train['arr_0']
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


In [ ]:
# reshape the data
X_train_reshape=X_train.reshape(60000,28*28)
X_test_reshape=X_test.reshape(10000,28*28)
print(X_train_reshape.shape)
print(X_test_reshape.shape)



(60000, 784)
(10000, 784)


In [ ]:
# Standaridise the data

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled=scaler.fit_transform(X_train_reshape)
X_test_scaled=scaler.transform(X_test_reshape)
print(X_train_scaled.shape)
print(X_test_scaled.shape)

(60000, 784)
(10000, 784)


In [ ]:
#apply PCA to 10 components
from sklearn.decomposition import PCA
pca=PCA(n_components=10)

X_train_pca=pca.fit_transform(X_train_scaled)
print(X_train_pca.shape)



(60000, 10)


In [ ]:
#appy pca to X_test_scaled
X_test_pca=pca.fit_transform(X_test_scaled)
print(X_test_pca.shape)

(10000, 10)


In [ ]:
# model1:apply the decisiontreemodel
dectree=DecisionTreeClassifier()
dectree.fit(X_train_pca,y_train)


DecisionTreeClassifier()

In [ ]:
y_predict_dectree=dectree.predict(X_test_pca)

In [ ]:
print(metrics.classification_report(y_test,y_predict_dectree))
print(metrics.confusion_matrix(y_test,y_predict_dectree))

              precision    recall  f1-score   support

           0       0.05      0.03      0.04      1000
           1       0.06      0.05      0.06      1000
           2       0.01      0.01      0.01      1000
           3       0.01      0.02      0.02      1000
           4       0.08      0.04      0.06      1000
           5       0.22      0.39      0.28      1000
           6       0.00      0.00      0.00      1000
           7       0.24      0.05      0.09      1000
           8       0.17      0.51      0.25      1000
           9       0.08      0.06      0.07      1000

    accuracy                           0.12     10000
   macro avg       0.09      0.12      0.09     10000
weighted avg       0.09      0.12      0.09     10000

[[ 27  47   8 308  73  99   8   5 413  12]
 [ 47  53  33 245 117  76  21   5 366  37]
 [  2   5  11   6  29 163   0   5 752  27]
 [ 99 157 379  18  25 234   0   7  34  47]
 [ 17 240  71 128  42 461   3   7  21  10]
 [ 30 113  44 123  35 392 

In [ ]:
print("Decision Tree Accuracy:", metrics.accuracy_score(y_test, y_predict_dectree))

Decision Tree Accuracy: 0.1169


In [ ]:
# Apply the model for different values of pca (pca=10,15,20,25,30)
#model1:Decisiontreeclassifier
pca_values=[10,15,20,25,30]

for n_components in pca_values:
  print(f"Applying PCA with {n_components} components")
  pca=PCA(n_components=n_components)
  X_train_pca=pca.fit_transform(X_train_scaled)
  X_test_pca=pca.transform(X_test_scaled)

  dectree=DecisionTreeClassifier()
  dectree.fit(X_train_pca,y_train)
  y_predict_dectree=dectree.predict(X_test_pca)

  print(metrics.classification_report(y_test,y_predict_dectree))
  print(metrics.confusion_matrix(y_test,y_predict_dectree))
  print("Decision tree accuracy", metrics.accuracy_score(y_test,y_predict_dectree))
  print("-" *75)



Applying PCA with 10 components
              precision    recall  f1-score   support

           0       0.81      0.74      0.77      1000
           1       0.78      0.81      0.80      1000
           2       0.97      0.97      0.97      1000
           3       0.70      0.78      0.74      1000
           4       0.73      0.81      0.77      1000
           5       0.80      0.76      0.78      1000
           6       0.75      0.74      0.75      1000
           7       0.71      0.61      0.66      1000
           8       0.82      0.86      0.84      1000
           9       0.88      0.88      0.88      1000

    accuracy                           0.80     10000
   macro avg       0.80      0.80      0.80     10000
weighted avg       0.80      0.80      0.80     10000

[[743 137   3  44   5   6   3   7  40  12]
 [ 62 814   2  40  17  34   2  16   8   5]
 [  4   2 975   1   1  15   0   1   0   1]
 [ 14  22   6 778  42  35  21  66   9   7]
 [  1   5   1  50 813  69   5   7  37

In [ ]:
# prompt: write above codes for random forest

#model2:Apply RandomForestClassifier
pca_values=[10,15,20,25,30]

for n_components in pca_values:
  print(f"Applying PCA with {n_components} components")
  pca=PCA(n_components=n_components)
  X_train_pca=pca.fit_transform(X_train_scaled)
  X_test_pca=pca.transform(X_test_scaled)

  rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42) # You can adjust n_estimators
  rf_classifier.fit(X_train_pca, y_train)
  y_pred_rf = rf_classifier.predict(X_test_pca)

  print(metrics.classification_report(y_test, y_pred_rf))
  print(metrics.confusion_matrix(y_test, y_pred_rf))
  print("Random Forest Accuracy:", metrics.accuracy_score(y_test, y_pred_rf))
  print("-" * 75)

In [ ]:
#Model:2 Random Forest
# Apply the model for different values of pca (pca=10,15,20,25,30)

pca_values=[10,15,20,25,30]

for n_components in pca_values:
  print(f"Applying PCA with {n_components} components")
  pca=PCA(n_components=n_components)
  X_train_pca=pca.fit_transform(X_train_scaled)
  X_test_pca=pca.transform(X_test_scaled)

  rf_classifier=RandomForestClassifier(n_estimators=100,random_state=42)
  rf_classifier.fit(X_train_pca,y_train)
  y_predict_rf=rf_classifier.predict(X_test_pca)

  print(metrics.classification_report(y_test,y_predict_rf))
  print(metrics.confusion_matrix(y_test,y_predict_rf))
  print("Decision tree accuracy", metrics.accuracy_score(y_test,y_predict_rf))
  print("-" *75)

Applying PCA with 10 components
              precision    recall  f1-score   support

           0       0.90      0.79      0.84      1000
           1       0.82      0.90      0.86      1000
           2       0.99      0.98      0.99      1000
           3       0.77      0.89      0.82      1000
           4       0.81      0.88      0.84      1000
           5       0.89      0.81      0.85      1000
           6       0.84      0.81      0.83      1000
           7       0.84      0.73      0.78      1000
           8       0.87      0.94      0.90      1000
           9       0.95      0.92      0.94      1000

    accuracy                           0.86     10000
   macro avg       0.87      0.86      0.86     10000
weighted avg       0.87      0.86      0.86     10000

[[788 144   0  41   2   1   2   1  19   2]
 [ 27 903   1  39   4  14   1   2   4   5]
 [  4   2 983   0   0  11   0   0   0   0]
 [  8  11   2 885  17  24   7  43   3   0]
 [  0   2   0  41 878  35   0   1  37

In [ ]:
# mode3:3 Naive Bayes model
# Apply the model for different values of pca (pca=10,15,20,25,30)

pca_values=[10,15,20,25,30]

for n_components in pca_values:
  print(f"Applying PCA with {n_components} components")
  pca=PCA(n_components=n_components)
  X_train_pca=pca.fit_transform(X_train_scaled)
  X_test_pca=pca.transform(X_test_scaled)

  gnb=GaussianNB()
  gnb.fit(X_train_pca,y_train)
  y_predict_gnb=gnb.predict(X_test_pca)


  print(metrics.classification_report(y_test,y_predict_gnb))
  print(metrics.confusion_matrix(y_test,y_predict_gnb))
  print("Gaussian Naiva Bayes accuracy", metrics.accuracy_score(y_test,y_predict_gnb))
  print("-" *75)

Applying PCA with 10 components
              precision    recall  f1-score   support

           0       0.75      0.68      0.71      1000
           1       0.77      0.71      0.74      1000
           2       0.98      0.97      0.97      1000
           3       0.48      0.85      0.62      1000
           4       0.62      0.82      0.71      1000
           5       0.80      0.62      0.70      1000
           6       0.79      0.72      0.75      1000
           7       0.65      0.40      0.50      1000
           8       0.81      0.74      0.77      1000
           9       0.89      0.78      0.84      1000

    accuracy                           0.73     10000
   macro avg       0.75      0.73      0.73     10000
weighted avg       0.75      0.73      0.73     10000

[[675 164   3  88  20   3   0   4  37   6]
 [ 18 711   3 185  16  24   0  20  10  13]
 [  5   2 972   2   0  18   0   0   1   0]
 [ 11   8   2 851  44  31  11  42   0   0]
 [  0   0   1  87 825  36   0   4  36

In [ ]:
#model:4 KNN Classifier

# Apply the model for different values of pca (pca=10,15,20,25,30)

pca_values=[10,15,20,25,30]

for n_components in pca_values:
  print(f"Applying PCA with {n_components} components")
  pca=PCA(n_components=n_components)
  X_train_pca=pca.fit_transform(X_train_scaled)
  X_test_pca=pca.transform(X_test_scaled)

  knn_classifier=KNeighborsClassifier(n_neighbors=5)
  knn_classifier.fit(X_train_pca,y_train)
  y_predict_knn=knn_classifier.predict(X_test_pca)

  print(metrics.classification_report(y_test,y_predict_knn))
  print(metrics.confusion_matrix(y_test,y_predict_knn))
  print(" KNN accuracy", metrics.accuracy_score(y_test,y_predict_knn))
  print("-" *75)

Applying PCA with 10 components
              precision    recall  f1-score   support

           0       0.89      0.80      0.84      1000
           1       0.82      0.94      0.88      1000
           2       1.00      0.99      0.99      1000
           3       0.80      0.88      0.84      1000
           4       0.80      0.91      0.85      1000
           5       0.91      0.82      0.86      1000
           6       0.83      0.84      0.83      1000
           7       0.86      0.72      0.78      1000
           8       0.91      0.95      0.93      1000
           9       0.97      0.94      0.95      1000

    accuracy                           0.88     10000
   macro avg       0.88      0.88      0.88     10000
weighted avg       0.88      0.88      0.88     10000

[[801 149   0  27   2   0   1   1  16   3]
 [ 22 936   0  21   6   8   1   2   4   0]
 [  2   2 988   1   0   7   0   0   0   0]
 [ 13  14   2 875  22  32   7  34   1   0]
 [  1   1   0  28 909  26   2   3  26

In [ ]:
#model:5 SVM
# Apply the model for different values of pca (pca=10,15,20,25,30)

pca_values=[10,15,20,25,30]

for n_components in pca_values:
  print(f"Applying PCA with {n_components} components")
  pca=PCA(n_components=n_components)
  X_train_pca=pca.fit_transform(X_train_scaled)
  X_test_pca=pca.transform(X_test_scaled)

  svm_classifier=SVC(kernel='linear',C=1)
  svm_classifier.fit(X_train_pca,y_train)
  y_predict_svm=svm_classifier.predict(X_test_pca)

  print(metrics.classification_report(y_test,y_predict_svm))
  print(metrics.confusion_matrix(y_test,y_predict_svm))
  print("SVM accuracy", metrics.accuracy_score(y_test,y_predict_svm))
  print("-" *75)

Applying PCA with 10 components
              precision    recall  f1-score   support

           0       0.88      0.77      0.82      1000
           1       0.81      0.89      0.85      1000
           2       0.98      0.97      0.98      1000
           3       0.72      0.85      0.78      1000
           4       0.80      0.88      0.84      1000
           5       0.88      0.81      0.85      1000
           6       0.80      0.67      0.73      1000
           7       0.73      0.69      0.71      1000
           8       0.85      0.93      0.89      1000
           9       0.92      0.88      0.90      1000

    accuracy                           0.83     10000
   macro avg       0.84      0.83      0.83     10000
weighted avg       0.84      0.83      0.83     10000

[[774 138   3  43   2   1   0   5  28   6]
 [ 31 888   7  39   5  15   0   5   7   3]
 [  5   5 973   1   0  10   0   0   6   0]
 [ 11  15   2 846  17  24   6  78   1   0]
 [  0   0   0  51 876  26   0   1  34